src/LBM/UserBundle/Entity/LbmUser.php
<?php

namespace LBM\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * LbmUser
 *
 * @ORM\Table(name="lbm_user_user")
 * @ORM\Entity(repositoryClass="LBM\UserBundle\Repository\LbmUserRepository")
 */
class LbmUser implements UserInterface
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=255, unique=true)
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255)
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="salt", type="string", length=255)
     */
    private $salt;

    /**
     * @var string
     *
     * @ORM\Column(name="avatar_url", type="string", length=255, nullable=true)
     */
    private $avatar_url;



    /**
     * @var array
     *
     * @ORM\Column(name="roles", type="array")
     */
    private $roles;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     *
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set password
     *
     * @param string $password
     *
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set salt
     *
     * @param string $salt
     *
     * @return User
     */
    public function setSalt($salt)
    {
        $this->salt = $salt;

        return $this;
    }

    /**
     * Get salt
     *
     * @return string
     */
    public function getSalt()
    {
        return $this->salt;
    }


    /**
     * Set avatar_url
     *
     * @param string $avatar_url
     *
     * @return User
     */
    public function setAvatarUrl($avatar_url)
    {
        $this->avatar_url = $avatar_url;

        return $this;
    }


    /**
     * get avatar_url
     *
     */
    public function getAvatarUrl()
    {
        return $this->avatar_url;
    }


    /**
     * Set roles
     *
     * @param array $roles
     *
     * @return User
     */
    public function setRoles($roles)
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * Get roles
     *
     * @return array
     */
    public function getRoles()
    {
        return $this->roles;
    }


    public function eraseCredentials()
    {
    }

}

src/LBM/UserBundle/Controller/DefaultController.php
<?php

namespace LBM\UserBundle\Controller;

use LBM\UserBundle\Entity\LbmUser;
use LBM\UserBundle\Entity\User;
use LBM\UserBundle\Form\LbmUserType;
use LBM\UserBundle\Form\UserType;
use LBM\UserBundle\LBMUserBundle;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;


class DefaultController extends Controller
{

    /**
     * @Route("/utilisateur.html", name="indexUser")
     */
    public function indexAction(Request $request)
    {

        $repository = $this->getDoctrine()
            ->getManager()
            ->getRepository('LBMUserBundle:LbmUser');

        $users = $repository->findAll();

        return $this->render(
            'LBMUserBundle:Default:index.html.twig',
            array(
                'users' => $users
            )
        );
    }

    /**
     * @Route("/creer-un-utilisateur.html", name="editUser")
     *
    public function editAction(Request $request)
    {
        $user = new LbmUser() ;
        $form = $this->createForm(
                                    LbmUserType::class, $user,
                                    array(
                                        'action' => $this->generateUrl('updateUser'),
                                    )
                                );

        return $this->render(
            'LBMUserBundle:Default:edit.html.twig',
                                                    array(
                                                        'form' => $form->createView()
                                                    )
        );
    }*/



    /**
     * @Route("/creer-un-utilisateur.html", name="createUser")
     * @Route("/modification-utilisateur-{user_id}.html", name="editUser")
    */
    public function editAction(Request $request, $user_id = null)
    {

        $repository = $this->getDoctrine()
            ->getManager()
            ->getRepository('LBMUserBundle:LbmUser');

        $user = $repository->findOneBy(array('id' => $user_id));

        $form = $this->createForm(LbmUserType::class, $user);

        return $this->render(
            'LBMUserBundle:Default:edit.html.twig',
            array(
                'form' => $form->createView(), 'user_id' => $user_id
            )
        );
    }

    /**
     * @Route("/mise-a-jour-utilisateur-{user_id}.html", name="updateUser")
     */
    public function updateAction(Request $request, $user_id = null)
    {

        if($user_id) {
            $repository = $this->getDoctrine()
                ->getManager()
                ->getRepository('LBMUserBundle:LbmUser');

            $user = $repository->findOneBy(array('id' => $user_id));
        } else {
            $user = new LbmUser();
        }


        $form = $this->createForm(LbmUserType::class, $user);

        if ($request->isMethod('POST')) {

            $form->handleRequest($request);
            
                $em = $this->getDoctrine()->getManager();
                $em->persist($user);
                $em->flush();

                $request->getSession()->getFlashBag()->add('notice', 'User ajouté.');
echo 'yes';
                return $this->redirectToRoute('indexUser');
            //}
        } else {
            echo "no";
        }

echo 'echec'; exit;
        return $this->redirectToRoute('editUser');


    }



    /**
     * @Route("/suppression-utilisateur.html", name="deleteUser")
     */
    public function deleteAction(Request $request)
    {


    }


    /**
     * @Route("/profile-statut.html", name="profileStatus")
     */
    public function profileStatusAction()
    {
        $user = $this->getUser();
        return $this->render(
                                'LBMUserBundle:Default:profileStatus.html.twig',
                                array(
                                    'user' => $user
                                )
                            );
    }


    /**
     * @Route("/profile-utilisateur.html", name="showProfile")
     */
    public function showProfilAction(Request $request)
    {
        $user = $this->getUser();

        return $this->render(
            'LBMUserBundle:Default:show.html.twig',
            array(
                'user' => $user
            )
        );
    }


    /**
     * @Route("/profile-settings.html", name="settingsProfile")
     */
    public function settingsAction()
    {
        $user = $this->getUser();

        $form = $this->createForm(LbmUserType::class, $user);

        return $this->render(
            'LBMUserBundle:Default:settings.html.twig',
            array(
                'user' => $user,
                'myForm' => $form->createView()
            )
        );
    }
}

src/LBM/UserBundle/Resources/views/Default/edit.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    {% form_theme form 'bootstrap_3_layout.html.twig' %}


    <div class="col-md-6">

        <section class="tile">

            <!-- tile header -->
            <div class="tile-header dvd dvd-btm">
                <h1 class="custom-font">Modifier un <strong>Utilisateur </strong></h1>

            </div>
            <!-- /tile header -->

            <!-- tile widget -->
            <div class="tile-body">

                <form action="{{ path('updateUser', {'user_id': user_id}) }}" method="post">

                    <div class='form-group'>
                        {{ form_label(form.username) }}
                        {{ form_errors(form.username) }}
                        {{ form_widget(form.username) }}
                    </div>

                    <div class='form-group'>
                        {{ form_label(form.password) }}
                        {{ form_errors(form.password) }}
                        {{ form_widget(form.password) }}
                    </div>

                    {{ form_rest(form) }}

                </form>

                <!-- /row -->


            </div>
            <!-- /tile widget -->



            <!-- /tile body -->

        </section>
        <!-- /tile -->



        <!-- /tile -->


    </div>



{% endblock %}

src/LBM/UserBundle/Resources/views/Default/index.html.twig
{% extends 'base.html.twig' %}


{% block subnavigation %}
   <button class="btn btn-primary btn-ef btn-ef-5 btn-ef-5b mb-10">
      <i class="fa fa-user-plus"></i>
      <span>Liste</span>
   </button>



   <button class="btn btn-primary btn-ef btn-ef-5 btn-ef-5b mb-10">
      <i class="fa fa-user-plus"></i>
      <span>Nouveau</span>
   </button>
{% endblock %}

{% block body %}


   <div class="col-md-6">

      <!-- tile -->
      <section class="tile">

         <!-- tile header -->
         <div class="tile-header dvd dvd-btm">
            <h1 class="custom-font"> Liste des <strong>Utilisateurs</strong></h1>

            <ul class="controls">
               <li>
                  <a role="button" href="{{ path('createUser') }}" title="Créer un nouvel utilisateur" style="color: grey">
                     <i class="fa fa-user-plus">
                     </i>
                  </a>
               </li>
            </ul>



         </div>
         <!-- /tile header -->

         <!-- tile body -->
         <div class="tile-body p-0">

            <table class="table table-striped">
               <thead>
               <tr>
                  <th  style="width: 200px"></th>
                  <th  style="width: 20px">#</th>
                  <th>Username</th>
                  <th>Avatar</th>
                  <th  style="width: 20px"></th>
               </tr>
               </thead>
               <tbody>

               {% if users is defined %}
                  {% for user in users %}

                     <tr>
                        <td>
                           <a href="{{ path('editUser',  {'user_id' : user.id} )   }}" style="color: black">

                              <button type="button" class="btn btn-rounded-20 btn-default btn-sm" style="width:30px;">
                                 <i class="fa fa-pencil"></i>
                              </button>

                              <button type="button" class="btn btn-rounded-20 btn-default btn-sm" style="width:30px;">
                                 <i class="fa fa-eye" style="margin-left: -2px;"></i>
                              </button>


                           </a>
                        </td>
                        <td>{{ user.id }}</td>
                        <td>{{ user.username }}</td>
                        <td>
                           {% if(user.avatarUrl) %}
                              <img src="{{ asset(user.avatarUrl) }}" alt="" class="img-circle size-30x30">
                           {% endif %}
                        </td>
                        <td>
                           <a href="{{ path('deleteUser') }}" style="color: black">
                              <i class="fa fa-trash"></i>
                           </a>
                        </td>
                     </tr>

                  {% endfor %}
               {% endif %}

               </tbody>
            </table>

         </div>
         <!-- /tile body -->

      </section>
      <!-- /tile -->


   </div>


{% endblock %}

src/LBM/UserBundle/Resources/views/Default/login.html.twig
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->



<head>

   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
   <title>EKA - Admin Dashboard</title>
   <link rel="icon" type="image/ico" href="{{ asset('minovate/assets/images/favicon.ico') }}" />
   <meta name="description" content="">
   <meta name="viewport" content="width=device-width, initial-scale=1">




   <!-- ============================================
   ================= Stylesheets ===================
   ============================================= -->
   <!-- vendor css files -->
   <link rel="stylesheet" href="{{ asset('minovate/assets/css/vendor/bootstrap.min.css') }}">
   <link rel="stylesheet" href="{{ asset('minovate/assets/css/vendor/animate.css') }}">
   <link rel="stylesheet" href="{{ asset('minovate/assets/css/vendor/font-awesome.min.css') }}">
   <!--<link rel="stylesheet" href="{{ asset('minovate/assets/js/vendor/animsition/css/animsition.min.css') }}">-->

   <!-- project main css files -->
   <link rel="stylesheet" href="{{ asset('minovate/assets/css/main.css') }}">
   <!--/ stylesheets -->



   <!-- ==========================================
   ================= Modernizr ===================
   =========================================== -->
   <script type="text/javascript" src="{{ asset('minovate/assets/js/vendor/modernizr/modernizr-2.8.3-respond-1.4.2.min.js') }}"></script>
   <!--/ modernizr -->

</head>





<body id="minovate" class="appWrapper">

<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->


<!-- ====================================================
================= Application Content ===================
===================================================== -->
<div id="wrap" class="animsition">

   <div class="page page-core page-login">

      <div class="text-center"><h3 class="text-light text-white"><span class="text-lightred">ENERGY KIDS </span>ACADEMY</h3></div>

      <div class="container w-420 p-15 bg-white mt-40 text-center">


         <h2 class="text-light text-greensea">ACCES</h2>



         {% if error %}
            <div class="alert alert-danger">{{ error.message }}</div>
         {% endif %}

         <form action="{{ path('login_check') }}" method="post" class="form-validation mt-20">
            <div class="form-group">
               <input type="text" id="username" name="_username" value="{{ last_username }}"  class="form-control underline-input" placeholder="utilisateur"/>
            </div>



            <div class="form-group">
               <input type="password" id="password" name="_password" placeholder="mot de passe" class="form-control underline-input"/>
            </div>


            <div class="form-group text-left mt-20">
               <input type="submit" value="Connexion" class="btn btn-greensea b-0 br-2 mr-5"/>
            </div>



         </form>

      </div>

   </div>



</div>
<!--/ Application Content -->














<!-- ============================================
============== Vendor JavaScripts ===============
============================================= -->

<script type="text/javascript" src="{{ asset('minovate/assets/js/vendor/jquery/jquery-1.11.2.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('minovate/assets/js/vendor/bootstrap/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('minovate/assets/js/vendor/jRespond/jRespond.min.js') }}"></script>


<script type="text/javascript" src="{{ asset('minovate/assets/js/vendor/sparkline/jquery.sparkline.min.js') }}"></script>

<script type="text/javascript" src="{{ asset('minovate/assets/js/vendor/slimscroll/jquery.slimscroll.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('minovate/assets/js/vendor/animsition/js/jquery.animsition.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('minovate/assets/js/vendor/screenfull/screenfull.min.js') }}"></script>


<!-- ============================================
============== Custom JavaScripts ===============
============================================= -->
<script type="text/javascript" src="{{ asset('minovate/assets/js/main.js') }}"></script>
<!--/ custom javascripts -->






<!-- ===============================================
============== Page Specific Scripts ===============
================================================ -->
<script>
   $(window).load(function(){


   });
</script>
<!--/ Page Specific Scripts -->



</body>
</html>

src/LBM/UserBundle/Resources/views/Default/profileStatus.html.twig
{% if user %}
    <li class="dropdown nav-profile">

        <a href class="dropdown-toggle" data-toggle="dropdown">
            <img src="{{ asset(user.avatarUrl) }}" alt="" class="img-circle size-30x30">
            <span>{{ user.userName }}<i class="fa fa-angle-down"></i></span>
        </a>

        <ul class="dropdown-menu animated littleFadeInRight" role="menu">

            <li>
                <a role="button" tabindex="0" href="{{ path('showProfile') }}">
                    <span class="badge bg-greensea pull-right">86%</span>
                    <i class="fa fa-user"></i>Profile
                </a>
            </li>
            <li>
                <a role="button" tabindex="0">
                    <span class="label bg-lightred pull-right">new</span>
                    <i class="fa fa-check"></i>Tasks
                </a>
            </li>
            <li>
                <a role="button" tabindex="0" href="{{ path('settingsProfile') }}">
                    <i class="fa fa-cog"></i>Settings
                </a>
            </li>
            <li class="divider"></li>
            <!--
            <li>
                <a role="button" tabindex="0">
                    <i class="fa fa-lock"></i>Lock
                </a>
            </li>-->
            <li>
                <a href="{{ path('logout') }}" role="button" tabindex="0">
                    <i class="fa fa-sign-out"></i>Logout
                </a>
            </li>

        </ul>

    </li>
{% endif %}

src/LBM/UserBundle/Resources/views/Default/settings.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    Settings {{ user.username }}

    <br/>
    {{ form(myForm) }}

{% endblock %}

src/LBM/UserBundle/Resources/views/Default/show.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    Hello {{ user.username }}

{% endblock %}